PREDEFINED_MODELS = [

    # ============================================================
    # TEXT / NLP
    # ============================================================

    {
        "id": "static-1",
        "source": "static",
        "name": "TextGen Pro",
        "description": "General-purpose language model for text generation, chat, and summarization.",
        "logo": None,
        "model_type": "Text",
        "category": "Natural Language Processing",
        "use_cases": "Content writing, chatbots, summarization, customer support",
        "features": "Long context, multilingual support, streaming responses",
        "technical_requirements": "REST API, JSON, API key",
        "api_available": True,
        "version": "2.1",
        "accuracy": "92%",
        "performance": "Fast",
        "monthly_price": 19.0,
        "yearly_price": 190.0,
        "rating": 4.8,
        "price_tier": "mid",
        "technical_level": "beginner",
        "quality": "high",
        "speed": "fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-2",
        "source": "static",
        "name": "NLP Master",
        "description": "Natural language processing model for classification and text analysis.",
        "logo": None,
        "model_type": "Text",
        "category": "Natural Language Processing",
        "use_cases": "Text classification, sentiment analysis, document analysis",
        "features": "Fast processing, text classification, multilingual support",
        "technical_requirements": "REST API, JSON",
        "api_available": True,
        "version": "1.5",
        "accuracy": "91%",
        "performance": "Fast",
        "monthly_price": 12.0,
        "yearly_price": 120.0,
        "rating": 4.5,
        "price_tier": "low",
        "technical_level": "beginner",
        "quality": "high",
        "speed": "fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-3",
        "source": "static",
        "name": "SummarizeAI",
        "description": "AI model designed to create concise summaries from long documents.",
        "logo": None,
        "model_type": "Text",
        "category": "Natural Language Processing",
        "use_cases": "Document summarization, research, news summaries",
        "features": "Long document support, concise summaries",
        "technical_requirements": "REST API, JSON",
        "api_available": True,
        "version": "2.0",
        "accuracy": "94%",
        "performance": "Fast",
        "monthly_price": 10.0,
        "yearly_price": 100.0,
        "rating": 4.6,
        "price_tier": "low",
        "technical_level": "beginner",
        "quality": "high",
        "speed": "fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-4",
        "source": "static",
        "name": "SentimentAI",
        "description": "Analyzes text and identifies positive, negative, and neutral sentiment.",
        "logo": None,
        "model_type": "Text",
        "category": "Natural Language Processing",
        "use_cases": "Reviews, customer feedback, social media analysis",
        "features": "Sentiment scoring, batch processing",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "1.2",
        "accuracy": "93%",
        "performance": "Very fast",
        "monthly_price": 8.0,
        "yearly_price": 80.0,
        "rating": 4.4,
        "price_tier": "low",
        "technical_level": "beginner",
        "quality": "high",
        "speed": "very_fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-5",
        "source": "static",
        "name": "TranslateX",
        "description": "Multilingual AI translation model for common business and communication needs.",
        "logo": None,
        "model_type": "Text",
        "category": "Natural Language Processing",
        "use_cases": "Translation, localization, multilingual applications",
        "features": "Multiple languages, fast translation",
        "technical_requirements": "REST API, JSON",
        "api_available": True,
        "version": "3.1",
        "accuracy": "90%",
        "performance": "Fast",
        "monthly_price": 14.0,
        "yearly_price": 140.0,
        "rating": 4.5,
        "price_tier": "low",
        "technical_level": "beginner",
        "quality": "high",
        "speed": "fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-6",
        "source": "static",
        "name": "ChatBot Lite",
        "description": "Lightweight conversational AI model for websites and customer support.",
        "logo": None,
        "model_type": "Chat",
        "category": "Conversational AI",
        "use_cases": "Customer support, website chatbots, FAQs",
        "features": "Fast responses, conversation memory",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "1.8",
        "accuracy": "89%",
        "performance": "Very fast",
        "monthly_price": 9.0,
        "yearly_price": 90.0,
        "rating": 4.3,
        "price_tier": "low",
        "technical_level": "beginner",
        "quality": "medium",
        "speed": "very_fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-7",
        "source": "static",
        "name": "ContentWriter AI",
        "description": "AI writing model for blogs, product descriptions, and marketing content.",
        "logo": None,
        "model_type": "Text",
        "category": "Content Generation",
        "use_cases": "Blogs, advertisements, product descriptions",
        "features": "SEO writing, templates, rewriting",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "2.4",
        "accuracy": "91%",
        "performance": "Fast",
        "monthly_price": 16.0,
        "yearly_price": 160.0,
        "rating": 4.6,
        "price_tier": "mid",
        "technical_level": "beginner",
        "quality": "high",
        "speed": "fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-8",
        "source": "static",
        "name": "LegalText AI",
        "description": "Text analysis model designed for basic legal document processing.",
        "logo": None,
        "model_type": "Text",
        "category": "Document AI",
        "use_cases": "Contract analysis, document classification",
        "features": "Keyword extraction, document analysis",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "1.3",
        "accuracy": "90%",
        "performance": "Moderate",
        "monthly_price": 22.0,
        "yearly_price": 220.0,
        "rating": 4.4,
        "price_tier": "mid",
        "technical_level": "intermediate",
        "quality": "high",
        "speed": "moderate",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-9",
        "source": "static",
        "name": "ResumeAI",
        "description": "Analyzes resumes and extracts skills, education, and experience.",
        "logo": None,
        "model_type": "Text",
        "category": "Human Resources AI",
        "use_cases": "Resume screening, recruitment, skill extraction",
        "features": "Resume parsing, skill detection",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "1.1",
        "accuracy": "92%",
        "performance": "Fast",
        "monthly_price": 13.0,
        "yearly_price": 130.0,
        "rating": 4.5,
        "price_tier": "low",
        "technical_level": "beginner",
        "quality": "high",
        "speed": "fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-10",
        "source": "static",
        "name": "EmailWriter",
        "description": "Generates professional emails from short instructions.",
        "logo": None,
        "model_type": "Text",
        "category": "Productivity AI",
        "use_cases": "Emails, business communication, customer responses",
        "features": "Email templates, tone selection",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "2.0",
        "accuracy": "94%",
        "performance": "Very fast",
        "monthly_price": 7.0,
        "yearly_price": 70.0,
        "rating": 4.7,
        "price_tier": "low",
        "technical_level": "beginner",
        "quality": "high",
        "speed": "very_fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },


    # ============================================================
    # COMPUTER VISION
    # ============================================================

    {
        "id": "static-11",
        "source": "static",
        "name": "VisionScan",
        "description": "Computer vision model for object detection and image classification.",
        "logo": None,
        "model_type": "Vision",
        "category": "Computer Vision",
        "use_cases": "Object detection, retail, quality inspection",
        "features": "Bounding boxes, confidence scores",
        "technical_requirements": "GPU recommended, REST API",
        "api_available": True,
        "version": "1.4",
        "accuracy": "89%",
        "performance": "Very fast",
        "monthly_price": 29.0,
        "yearly_price": 290.0,
        "rating": 4.6,
        "price_tier": "mid",
        "technical_level": "intermediate",
        "quality": "high",
        "speed": "very_fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-12",
        "source": "static",
        "name": "FaceDetect AI",
        "description": "Detects faces in images and video streams.",
        "logo": None,
        "model_type": "Vision",
        "category": "Computer Vision",
        "use_cases": "Face detection, security, photo applications",
        "features": "Real-time detection, confidence scoring",
        "technical_requirements": "GPU optional, REST API",
        "api_available": True,
        "version": "2.0",
        "accuracy": "94%",
        "performance": "Very fast",
        "monthly_price": 18.0,
        "yearly_price": 180.0,
        "rating": 4.5,
        "price_tier": "mid",
        "technical_level": "intermediate",
        "quality": "high",
        "speed": "very_fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-13",
        "source": "static",
        "name": "ImageClassify",
        "description": "Classifies images into predefined categories.",
        "logo": None,
        "model_type": "Vision",
        "category": "Computer Vision",
        "use_cases": "Image classification, product recognition",
        "features": "Fast classification, batch processing",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "1.6",
        "accuracy": "91%",
        "performance": "Fast",
        "monthly_price": 15.0,
        "yearly_price": 150.0,
        "rating": 4.4,
        "price_tier": "low",
        "technical_level": "beginner",
        "quality": "high",
        "speed": "fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-14",
        "source": "static",
        "name": "OCR Vision",
        "description": "Extracts text from scanned documents and images.",
        "logo": None,
        "model_type": "Vision",
        "category": "Computer Vision",
        "use_cases": "Document scanning, invoice processing, OCR",
        "features": "Text extraction, multiple image formats",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "3.0",
        "accuracy": "95%",
        "performance": "Fast",
        "monthly_price": 17.0,
        "yearly_price": 170.0,
        "rating": 4.7,
        "price_tier": "mid",
        "technical_level": "beginner",
        "quality": "high",
        "speed": "fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-15",
        "source": "static",
        "name": "MedicalImage AI",
        "description": "Demonstration model for basic medical image classification research.",
        "logo": None,
        "model_type": "Vision",
        "category": "Healthcare AI",
        "use_cases": "Image classification, research, medical imaging",
        "features": "Image analysis, confidence scores",
        "technical_requirements": "GPU recommended",
        "api_available": False,
        "version": "1.0",
        "accuracy": "87%",
        "performance": "Moderate",
        "monthly_price": 35.0,
        "yearly_price": 350.0,
        "rating": 4.2,
        "price_tier": "high",
        "technical_level": "advanced",
        "quality": "medium",
        "speed": "moderate",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },


    # ============================================================
    # CODING
    # ============================================================

    {
        "id": "static-16",
        "source": "static",
        "name": "CodeAssist",
        "description": "Coding assistant for code completion, explanation, and refactoring.",
        "logo": None,
        "model_type": "Coding",
        "category": "Developer Tools",
        "use_cases": "Code completion, debugging, refactoring",
        "features": "Multiple languages, code explanation",
        "technical_requirements": "REST API or IDE plugin",
        "api_available": True,
        "version": "3.0",
        "accuracy": "95%",
        "performance": "Fast",
        "monthly_price": 25.0,
        "yearly_price": 250.0,
        "rating": 4.9,
        "price_tier": "mid",
        "technical_level": "advanced",
        "quality": "high",
        "speed": "fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-17",
        "source": "static",
        "name": "PythonPilot",
        "description": "AI coding assistant focused on Python development.",
        "logo": None,
        "model_type": "Coding",
        "category": "Developer Tools",
        "use_cases": "Python coding, debugging, learning",
        "features": "Code generation, explanations, debugging",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "2.2",
        "accuracy": "94%",
        "performance": "Fast",
        "monthly_price": 18.0,
        "yearly_price": 180.0,
        "rating": 4.8,
        "price_tier": "mid",
        "technical_level": "intermediate",
        "quality": "high",
        "speed": "fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-18",
        "source": "static",
        "name": "BugFinder",
        "description": "Analyzes source code and identifies common programming errors.",
        "logo": None,
        "model_type": "Coding",
        "category": "Developer Tools",
        "use_cases": "Bug detection, code review, debugging",
        "features": "Error detection, suggestions",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "1.7",
        "accuracy": "90%",
        "performance": "Fast",
        "monthly_price": 14.0,
        "yearly_price": 140.0,
        "rating": 4.5,
        "price_tier": "low",
        "technical_level": "intermediate",
        "quality": "high",
        "speed": "fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-19",
        "source": "static",
        "name": "SQLGen",
        "description": "Converts natural language questions into SQL queries.",
        "logo": None,
        "model_type": "Coding",
        "category": "Database AI",
        "use_cases": "SQL generation, database analysis",
        "features": "Natural language SQL, query explanation",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "1.9",
        "accuracy": "93%",
        "performance": "Fast",
        "monthly_price": 11.0,
        "yearly_price": 110.0,
        "rating": 4.6,
        "price_tier": "low",
        "technical_level": "intermediate",
        "quality": "high",
        "speed": "fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-20",
        "source": "static",
        "name": "TestGen AI",
        "description": "Generates basic software test cases from source code.",
        "logo": None,
        "model_type": "Coding",
        "category": "Developer Tools",
        "use_cases": "Unit tests, test generation, QA automation",
        "features": "Automatic test suggestions",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "2.1",
        "accuracy": "91%",
        "performance": "Moderate",
        "monthly_price": 20.0,
        "yearly_price": 200.0,
        "rating": 4.4,
        "price_tier": "mid",
        "technical_level": "advanced",
        "quality": "high",
        "speed": "moderate",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },


    # ============================================================
    # AUDIO / SPEECH
    # ============================================================

    {
        "id": "static-21",
        "source": "static",
        "name": "VoiceCraft",
        "description": "Text-to-speech model for natural voice generation.",
        "logo": None,
        "model_type": "Audio",
        "category": "Speech & Audio",
        "use_cases": "Voiceovers, audiobooks, accessibility",
        "features": "Multiple voices, streaming audio",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "1.0",
        "accuracy": "88%",
        "performance": "Moderate",
        "monthly_price": 15.0,
        "yearly_price": 150.0,
        "rating": 4.5,
        "price_tier": "low",
        "technical_level": "beginner",
        "quality": "medium",
        "speed": "moderate",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-22",
        "source": "static",
        "name": "SpeechToText",
        "description": "Converts recorded or streamed speech into text.",
        "logo": None,
        "model_type": "Audio",
        "category": "Speech & Audio",
        "use_cases": "Transcription, meetings, subtitles",
        "features": "Fast transcription, timestamps",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "2.5",
        "accuracy": "94%",
        "performance": "Fast",
        "monthly_price": 16.0,
        "yearly_price": 160.0,
        "rating": 4.7,
        "price_tier": "mid",
        "technical_level": "beginner",
        "quality": "high",
        "speed": "fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-23",
        "source": "static",
        "name": "MusicGen Lite",
        "description": "Generates short musical audio clips from text descriptions.",
        "logo": None,
        "model_type": "Audio",
        "category": "Generative AI",
        "use_cases": "Background music, prototypes, creative projects",
        "features": "Text-to-music, multiple styles",
        "technical_requirements": "GPU recommended",
        "api_available": False,
        "version": "1.1",
        "accuracy": "86%",
        "performance": "Moderate",
        "monthly_price": 21.0,
        "yearly_price": 210.0,
        "rating": 4.2,
        "price_tier": "mid",
        "technical_level": "advanced",
        "quality": "medium",
        "speed": "moderate",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-24",
        "source": "static",
        "name": "AudioClean",
        "description": "Removes common background noise from recorded audio.",
        "logo": None,
        "model_type": "Audio",
        "category": "Speech & Audio",
        "use_cases": "Podcast cleanup, calls, recordings",
        "features": "Noise reduction, voice enhancement",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "1.4",
        "accuracy": "90%",
        "performance": "Fast",
        "monthly_price": 12.0,
        "yearly_price": 120.0,
        "rating": 4.5,
        "price_tier": "low",
        "technical_level": "beginner",
        "quality": "high",
        "speed": "fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-25",
        "source": "static",
        "name": "VoiceTranslate",
        "description": "Translates spoken audio into another language.",
        "logo": None,
        "model_type": "Audio",
        "category": "Speech & Audio",
        "use_cases": "Meetings, travel, multilingual communication",
        "features": "Speech recognition and translation",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "2.0",
        "accuracy": "89%",
        "performance": "Moderate",
        "monthly_price": 19.0,
        "yearly_price": 190.0,
        "rating": 4.4,
        "price_tier": "mid",
        "technical_level": "intermediate",
        "quality": "high",
        "speed": "moderate",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },


    # ============================================================
    # IMAGE GENERATION
    # ============================================================

    {
        "id": "static-26",
        "source": "static",
        "name": "ArtGen",
        "description": "Generates creative images from text descriptions.",
        "logo": None,
        "model_type": "Image",
        "category": "Image Generation",
        "use_cases": "Digital art, marketing, creative projects",
        "features": "Text-to-image, multiple styles",
        "technical_requirements": "GPU or image API",
        "api_available": True,
        "version": "2.2",
        "accuracy": "90%",
        "performance": "Moderate",
        "monthly_price": 20.0,
        "yearly_price": 200.0,
        "rating": 4.7,
        "price_tier": "mid",
        "technical_level": "intermediate",
        "quality": "high",
        "speed": "moderate",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-27",
        "source": "static",
        "name": "PhotoEnhance",
        "description": "Improves image quality and resolution using AI.",
        "logo": None,
        "model_type": "Image",
        "category": "Image Processing",
        "use_cases": "Photo enhancement, upscaling, restoration",
        "features": "Upscaling, sharpening, enhancement",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "1.8",
        "accuracy": "92%",
        "performance": "Fast",
        "monthly_price": 13.0,
        "yearly_price": 130.0,
        "rating": 4.6,
        "price_tier": "low",
        "technical_level": "beginner",
        "quality": "high",
        "speed": "fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-28",
        "source": "static",
        "name": "BackgroundRemover",
        "description": "Automatically removes backgrounds from product and portrait images.",
        "logo": None,
        "model_type": "Image",
        "category": "Image Processing",
        "use_cases": "E-commerce, product photography, portraits",
        "features": "Automatic background removal",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "3.0",
        "accuracy": "95%",
        "performance": "Very fast",
        "monthly_price": 9.0,
        "yearly_price": 90.0,
        "rating": 4.8,
        "price_tier": "low",
        "technical_level": "beginner",
        "quality": "high",
        "speed": "very_fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-29",
        "source": "static",
        "name": "LogoMaker AI",
        "description": "Generates simple logo concepts from business descriptions.",
        "logo": None,
        "model_type": "Image",
        "category": "Design AI",
        "use_cases": "Logos, branding, business design",
        "features": "Text-to-logo, style selection",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "1.5",
        "accuracy": "88%",
        "performance": "Moderate",
        "monthly_price": 11.0,
        "yearly_price": 110.0,
        "rating": 4.3,
        "price_tier": "low",
        "technical_level": "beginner",
        "quality": "medium",
        "speed": "moderate",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-30",
        "source": "static",
        "name": "SketchToImage",
        "description": "Converts rough sketches into polished concept images.",
        "logo": None,
        "model_type": "Image",
        "category": "Design AI",
        "use_cases": "Concept art, product design, creative work",
        "features": "Sketch transformation, style control",
        "technical_requirements": "GPU recommended",
        "api_available": False,
        "version": "1.0",
        "accuracy": "87%",
        "performance": "Moderate",
        "monthly_price": 24.0,
        "yearly_price": 240.0,
        "rating": 4.4,
        "price_tier": "mid",
        "technical_level": "intermediate",
        "quality": "high",
        "speed": "moderate",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },


    # ============================================================
    # DATA / BUSINESS AI
    # ============================================================

    {
        "id": "static-31",
        "source": "static",
        "name": "DataPredict",
        "description": "Basic machine learning model for predicting numerical outcomes.",
        "logo": None,
        "model_type": "Prediction",
        "category": "Data Science",
        "use_cases": "Forecasting, prediction, business analytics",
        "features": "Prediction API, JSON output",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "1.3",
        "accuracy": "89%",
        "performance": "Fast",
        "monthly_price": 18.0,
        "yearly_price": 180.0,
        "rating": 4.3,
        "price_tier": "mid",
        "technical_level": "intermediate",
        "quality": "high",
        "speed": "fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-32",
        "source": "static",
        "name": "SalesForecast AI",
        "description": "Forecasts future sales using historical business data.",
        "logo": None,
        "model_type": "Prediction",
        "category": "Business AI",
        "use_cases": "Sales forecasting, inventory planning",
        "features": "Time-series forecasting",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "2.0",
        "accuracy": "91%",
        "performance": "Fast",
        "monthly_price": 23.0,
        "yearly_price": 230.0,
        "rating": 4.5,
        "price_tier": "mid",
        "technical_level": "intermediate",
        "quality": "high",
        "speed": "fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-33",
        "source": "static",
        "name": "FraudDetect",
        "description": "Detects potentially suspicious transactions using machine learning.",
        "logo": None,
        "model_type": "Prediction",
        "category": "Finance AI",
        "use_cases": "Fraud detection, transaction monitoring",
        "features": "Risk scoring, anomaly detection",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "2.4",
        "accuracy": "93%",
        "performance": "Fast",
        "monthly_price": 31.0,
        "yearly_price": 310.0,
        "rating": 4.7,
        "price_tier": "high",
        "technical_level": "advanced",
        "quality": "high",
        "speed": "fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-34",
        "source": "static",
        "name": "CustomerChurn AI",
        "description": "Predicts which customers may stop using a service.",
        "logo": None,
        "model_type": "Prediction",
        "category": "Business AI",
        "use_cases": "Customer retention, business analytics",
        "features": "Risk scoring, customer analysis",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "1.7",
        "accuracy": "90%",
        "performance": "Fast",
        "monthly_price": 21.0,
        "yearly_price": 210.0,
        "rating": 4.4,
        "price_tier": "mid",
        "technical_level": "intermediate",
        "quality": "high",
        "speed": "fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-35",
        "source": "static",
        "name": "DemandPredict",
        "description": "Predicts product demand from historical sales information.",
        "logo": None,
        "model_type": "Prediction",
        "category": "Business AI",
        "use_cases": "Demand planning, inventory management",
        "features": "Forecasting, trend analysis",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "1.9",
        "accuracy": "88%",
        "performance": "Moderate",
        "monthly_price": 19.0,
        "yearly_price": 190.0,
        "rating": 4.3,
        "price_tier": "mid",
        "technical_level": "intermediate",
        "quality": "medium",
        "speed": "moderate",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },


    # ============================================================
    # DOCUMENT / PRODUCTIVITY AI
    # ============================================================

    {
        "id": "static-36",
        "source": "static",
        "name": "DocumentAI",
        "description": "Extracts structured information from business documents.",
        "logo": None,
        "model_type": "Document",
        "category": "Document AI",
        "use_cases": "Invoices, forms, business documents",
        "features": "Document parsing, field extraction",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "2.2",
        "accuracy": "93%",
        "performance": "Fast",
        "monthly_price": 20.0,
        "yearly_price": 200.0,
        "rating": 4.6,
        "price_tier": "mid",
        "technical_level": "intermediate",
        "quality": "high",
        "speed": "fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-37",
        "source": "static",
        "name": "InvoiceReader",
        "description": "Extracts invoice numbers, dates, prices, and vendor information.",
        "logo": None,
        "model_type": "Document",
        "category": "Business AI",
        "use_cases": "Invoice processing, accounting automation",
        "features": "Field extraction, structured output",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "1.6",
        "accuracy": "95%",
        "performance": "Very fast",
        "monthly_price": 14.0,
        "yearly_price": 140.0,
        "rating": 4.7,
        "price_tier": "low",
        "technical_level": "beginner",
        "quality": "high",
        "speed": "very_fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-38",
        "source": "static",
        "name": "MeetingNotes AI",
        "description": "Creates summaries and action items from meeting transcripts.",
        "logo": None,
        "model_type": "Text",
        "category": "Productivity AI",
        "use_cases": "Meeting summaries, action items, notes",
        "features": "Summarization, action extraction",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "1.5",
        "accuracy": "92%",
        "performance": "Fast",
        "monthly_price": 12.0,
        "yearly_price": 120.0,
        "rating": 4.6,
        "price_tier": "low",
        "technical_level": "beginner",
        "quality": "high",
        "speed": "fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-39",
        "source": "static",
        "name": "ResearchAssist",
        "description": "Helps analyze and summarize research documents.",
        "logo": None,
        "model_type": "Text",
        "category": "Research AI",
        "use_cases": "Research, document analysis, summaries",
        "features": "Document search, summarization",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "2.1",
        "accuracy": "91%",
        "performance": "Moderate",
        "monthly_price": 17.0,
        "yearly_price": 170.0,
        "rating": 4.5,
        "price_tier": "mid",
        "technical_level": "intermediate",
        "quality": "high",
        "speed": "moderate",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-40",
        "source": "static",
        "name": "KnowledgeBot",
        "description": "Answers questions using a provided knowledge base.",
        "logo": None,
        "model_type": "Chat",
        "category": "Knowledge AI",
        "use_cases": "Internal knowledge bases, support systems",
        "features": "Document search, question answering",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "2.0",
        "accuracy": "93%",
        "performance": "Fast",
        "monthly_price": 16.0,
        "yearly_price": 160.0,
        "rating": 4.7,
        "price_tier": "mid",
        "technical_level": "intermediate",
        "quality": "high",
        "speed": "fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },


    # ============================================================
    # SPECIALIZED MODELS
    # ============================================================

    {
        "id": "static-41",
        "source": "static",
        "name": "RecommendationAI",
        "description": "Recommends products or content based on user preferences.",
        "logo": None,
        "model_type": "Recommendation",
        "category": "Recommendation AI",
        "use_cases": "Product recommendations, content discovery",
        "features": "Preference matching, ranking",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "1.4",
        "accuracy": "90%",
        "performance": "Fast",
        "monthly_price": 18.0,
        "yearly_price": 180.0,
        "rating": 4.5,
        "price_tier": "mid",
        "technical_level": "intermediate",
        "quality": "high",
        "speed": "fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-42",
        "source": "static",
        "name": "AnomalyDetector",
        "description": "Identifies unusual patterns in numerical datasets.",
        "logo": None,
        "model_type": "Prediction",
        "category": "Data Science",
        "use_cases": "Monitoring, fraud detection, system analysis",
        "features": "Anomaly scoring, statistical analysis",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "1.8",
        "accuracy": "91%",
        "performance": "Very fast",
        "monthly_price": 15.0,
        "yearly_price": 150.0,
        "rating": 4.4,
        "price_tier": "low",
        "technical_level": "intermediate",
        "quality": "high",
        "speed": "very_fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-43",
        "source": "static",
        "name": "WeatherPredict",
        "description": "Demonstration forecasting model for weather-related numerical data.",
        "logo": None,
        "model_type": "Prediction",
        "category": "Forecasting AI",
        "use_cases": "Weather forecasting, research, analytics",
        "features": "Time-series prediction",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "1.2",
        "accuracy": "86%",
        "performance": "Moderate",
        "monthly_price": 10.0,
        "yearly_price": 100.0,
        "rating": 4.1,
        "price_tier": "low",
        "technical_level": "advanced",
        "quality": "medium",
        "speed": "moderate",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-44",
        "source": "static",
        "name": "SpamShield",
        "description": "Classifies emails and messages as spam or legitimate.",
        "logo": None,
        "model_type": "Classification",
        "category": "Security AI",
        "use_cases": "Email filtering, message classification",
        "features": "Spam scoring, fast classification",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "3.2",
        "accuracy": "96%",
        "performance": "Very fast",
        "monthly_price": 8.0,
        "yearly_price": 80.0,
        "rating": 4.8,
        "price_tier": "low",
        "technical_level": "beginner",
        "quality": "high",
        "speed": "very_fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-45",
        "source": "static",
        "name": "LanguageDetect",
        "description": "Identifies the language used in a text input.",
        "logo": None,
        "model_type": "Classification",
        "category": "Natural Language Processing",
        "use_cases": "Language detection, multilingual applications",
        "features": "Fast language identification",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "2.3",
        "accuracy": "97%",
        "performance": "Very fast",
        "monthly_price": 6.0,
        "yearly_price": 60.0,
        "rating": 4.8,
        "price_tier": "low",
        "technical_level": "beginner",
        "quality": "high",
        "speed": "very_fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-46",
        "source": "static",
        "name": "KeywordExtractor",
        "description": "Extracts important keywords and phrases from documents.",
        "logo": None,
        "model_type": "Text",
        "category": "Natural Language Processing",
        "use_cases": "SEO, document analysis, search",
        "features": "Keyword ranking, phrase extraction",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "1.9",
        "accuracy": "92%",
        "performance": "Very fast",
        "monthly_price": 7.0,
        "yearly_price": 70.0,
        "rating": 4.5,
        "price_tier": "low",
        "technical_level": "beginner",
        "quality": "high",
        "speed": "very_fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-47",
        "source": "static",
        "name": "ImageCaption AI",
        "description": "Generates descriptions of images using computer vision.",
        "logo": None,
        "model_type": "Vision",
        "category": "Computer Vision",
        "use_cases": "Accessibility, image search, photo descriptions",
        "features": "Automatic captions, visual analysis",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "1.6",
        "accuracy": "90%",
        "performance": "Fast",
        "monthly_price": 13.0,
        "yearly_price": 130.0,
        "rating": 4.5,
        "price_tier": "low",
        "technical_level": "intermediate",
        "quality": "high",
        "speed": "fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-48",
        "source": "static",
        "name": "ProductClassifier",
        "description": "Classifies products into predefined categories from product information.",
        "logo": None,
        "model_type": "Classification",
        "category": "E-commerce AI",
        "use_cases": "Product catalogs, e-commerce, inventory",
        "features": "Automatic categorization",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "2.0",
        "accuracy": "94%",
        "performance": "Fast",
        "monthly_price": 14.0,
        "yearly_price": 140.0,
        "rating": 4.6,
        "price_tier": "low",
        "technical_level": "beginner",
        "quality": "high",
        "speed": "fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-49",
        "source": "static",
        "name": "SocialAnalyzer",
        "description": "Analyzes social media text for sentiment and common topics.",
        "logo": None,
        "model_type": "Text",
        "category": "Social Media AI",
        "use_cases": "Social media monitoring, sentiment analysis",
        "features": "Topic extraction, sentiment analysis",
        "technical_requirements": "REST API",
        "api_available": True,
        "version": "1.8",
        "accuracy": "91%",
        "performance": "Fast",
        "monthly_price": 16.0,
        "yearly_price": 160.0,
        "rating": 4.4,
        "price_tier": "mid",
        "technical_level": "intermediate",
        "quality": "high",
        "speed": "fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },

    {
        "id": "static-50",
        "source": "static",
        "name": "AI Assistant Pro",
        "description": "General-purpose AI assistant for text, research, productivity, and business tasks.",
        "logo": None,
        "model_type": "Chat",
        "category": "General AI",
        "use_cases": "Research, writing, productivity, customer support",
        "features": "Chat, summarization, reasoning, document analysis",
        "technical_requirements": "REST API, JSON",
        "api_available": True,
        "version": "4.0",
        "accuracy": "96%",
        "performance": "Fast",
        "monthly_price": 30.0,
        "yearly_price": 300.0,
        "rating": 4.9,
        "price_tier": "high",
        "technical_level": "intermediate",
        "quality": "high",
        "speed": "fast",
        "creator_name": "AI Marketplace Team",
        "creator_bio": "Curated demonstration model.",
        "creator_verified": True,
    },
]


def get_predefined_model_by_id(model_id: str):
    """Look up a single static model by its 'static-N' id, or None if missing."""
    for m in PREDEFINED_MODELS:
        if m["id"] == model_id:
            return m
    return None